//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryCommander.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryCommander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string AddOperation {
            get {
                return ResourceManager.GetString("AddOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author cannot be empty.
        /// </summary>
        internal static string AuthorsError {
            get {
                return ResourceManager.GetString("AuthorsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select author(s).
        /// </summary>
        internal static string AuthorsTitle {
            get {
                return ResourceManager.GetString("AuthorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library contains book(s) of author [{0}].
        /// </summary>
        internal static string AuthorUsageWarning {
            get {
                return ResourceManager.GetString("AuthorUsageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Card.
        /// </summary>
        internal static string CardWindow {
            get {
                return ResourceManager.GetString("CardWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be empty.
        /// </summary>
        internal static string CategoryError {
            get {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library contains books(s) in [{0}] category.
        /// </summary>
        internal static string CategoryUsageWarning {
            get {
                return ResourceManager.GetString("CategoryUsageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Cmd {
            get {
                return ResourceManager.GetString("Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cycle.
        /// </summary>
        internal static string CycleTitle {
            get {
                return ResourceManager.GetString("CycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book deletion.
        /// </summary>
        internal static string DeleteBookCaption {
            get {
                return ResourceManager.GetString("DeleteBookCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete [{0}] from library?.
        /// </summary>
        internal static string DeleteBookQuestion {
            get {
                return ResourceManager.GetString("DeleteBookQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete [{0}] from list?.
        /// </summary>
        internal static string DeleteItemQuestion {
            get {
                return ResourceManager.GetString("DeleteItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        internal static string DeleteOperation {
            get {
                return ResourceManager.GetString("DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create duplicate record.
        /// </summary>
        internal static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown object.
        /// </summary>
        internal static string EntityError {
            get {
                return ResourceManager.GetString("EntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file.
        /// </summary>
        internal static string FileDelete {
            get {
                return ResourceManager.GetString("FileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving file.
        /// </summary>
        internal static string FileMove {
            get {
                return ResourceManager.GetString("FileMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path cannot be empty.
        /// </summary>
        internal static string FilePathError {
            get {
                return ResourceManager.GetString("FilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file.
        /// </summary>
        internal static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select book.
        /// </summary>
        internal static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileWarning {
            get {
                object obj = ResourceManager.GetObject("fileWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderWarning {
            get {
                object obj = ResourceManager.GetObject("folderWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format cannot be empty.
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select format.
        /// </summary>
        internal static string FormatTitle {
            get {
                return ResourceManager.GetString("FormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library contains books(s) in [{0}] format.
        /// </summary>
        internal static string FormatUsageWarning {
            get {
                return ResourceManager.GetString("FormatUsageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language cannot be empty.
        /// </summary>
        internal static string LanguageError {
            get {
                return ResourceManager.GetString("LanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library contains book(s) in language [{0}].
        /// </summary>
        internal static string LanguageUsageWarning {
            get {
                return ResourceManager.GetString("LanguageUsageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Library.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be Null.
        /// </summary>
        internal static string NullError {
            get {
                return ResourceManager.GetString("NullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags cannot be empty.
        /// </summary>
        internal static string TagsError {
            get {
                return ResourceManager.GetString("TagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tag(s).
        /// </summary>
        internal static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateOperation {
            get {
                return ResourceManager.GetString("UpdateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.
        /// </summary>
        internal static string ValueError {
            get {
                return ResourceManager.GetString("ValueError", resourceCulture);
            }
        }
    }
}
